import type { FieldGroup } from "../types";

export const closingGroup: FieldGroup = {
  id: "closing",
  label: "Timeline & Budget",
  description: "Last few questions so we can put together a realistic proposal.",
  sortOrder: 2,
  step: 3,
  fields: [
    {
      id: "closing.timeline",
      groupId: "closing",
      type: "radio-group",
      label: "When do you need this done?",
      options: [
        { value: "asap", label: "As soon as possible" },
        { value: "1-2-months", label: "Within 1-2 months" },
        { value: "3-6-months", label: "3-6 months" },
        { value: "flexible", label: "No rush — whenever it's ready" },
      ],
      validation: { required: true },
      layout: "full",
      sortOrder: 1,
    },
    {
      id: "closing.budget",
      groupId: "closing",
      type: "radio-group",
      label: "What's your approximate budget?",
      options: [
        { value: "under-1k", label: "Under $1,000" },
        { value: "1k-5k", label: "$1,000 – $5,000" },
        { value: "5k-15k", label: "$5,000 – $15,000" },
        { value: "15k-plus", label: "$15,000+" },
        { value: "unsure", label: "Not sure yet" },
      ],
      validation: { required: true },
      layout: "full",
      sortOrder: 2,
    },
    {
      id: "closing.decisionMaker",
      groupId: "closing",
      type: "radio-group",
      label: "Are you the decision-maker for this project?",
      options: [
        { value: "yes", label: "Yes" },
        { value: "no", label: "No — someone else will approve" },
        { value: "shared", label: "It's a shared decision" },
      ],
      validation: { required: true },
      layout: "half",
      sortOrder: 3,
    },
    {
      id: "closing.preferredContact",
      groupId: "closing",
      type: "radio-group",
      label: "How should we reach you?",
      options: [
        { value: "email", label: "Email" },
        { value: "phone", label: "Phone" },
        { value: "text", label: "Text message" },
        { value: "any", label: "Any of the above" },
      ],
      validation: { required: true },
      layout: "half",
      sortOrder: 4,
    },
    {
      id: "closing.additionalNotes",
      groupId: "closing",
      type: "textarea",
      label: "Anything else we should know?",
      placeholder: "For example: team size, hosting preferences, must-use tools, concerns...",
      validation: { required: false, maxLength: 2000 },
      rows: 4,
      layout: "full",
      sortOrder: 5,
    },
    {
      id: "closing.howDidYouFindUs",
      groupId: "closing",
      type: "select",
      label: "How did you hear about us?",
      options: [
        { value: "google", label: "Google search" },
        { value: "social-media", label: "Social media" },
        { value: "referral", label: "Referral from someone" },
        { value: "directory", label: "Online directory" },
        { value: "other", label: "Other" },
      ],
      validation: { required: false },
      layout: "half",
      sortOrder: 6,
    },
  ],
};
