import type { FieldGroup } from "../types";

export const contactGroup: FieldGroup = {
  id: "contact",
  label: "About You & Your Business",
  description: "Let's start with the basics so we can get back to you.",
  sortOrder: 1,
  step: 1,
  fields: [
    {
      id: "contact.fullName",
      groupId: "contact",
      type: "text",
      label: "Full Name",
      placeholder: "Jane Smith",
      validation: { required: true, maxLength: 100 },
      layout: "half",
      sortOrder: 1,
    },
    {
      id: "contact.email",
      groupId: "contact",
      type: "text",
      label: "Email Address",
      placeholder: "jane@example.com",
      validation: {
        required: true,
        pattern: {
          regex: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$",
          message: "Please enter a valid email address",
        },
      },
      inputType: "email",
      layout: "half",
      sortOrder: 2,
    },
    {
      id: "contact.phone",
      groupId: "contact",
      type: "text",
      label: "Phone Number",
      placeholder: "(555) 123-4567",
      validation: { required: false },
      inputType: "tel",
      layout: "half",
      sortOrder: 3,
    },
    {
      id: "contact.businessName",
      groupId: "contact",
      type: "text",
      label: "Business Name",
      placeholder: "Acme Inc.",
      validation: { required: true, maxLength: 150 },
      layout: "half",
      sortOrder: 4,
    },
    {
      id: "contact.businessDescription",
      groupId: "contact",
      type: "textarea",
      label: "What does your business do?",
      placeholder: "We sell handmade candles online and at local markets...",
      helpText: "A sentence or two is plenty.",
      validation: { required: true, maxLength: 500 },
      rows: 3,
      layout: "full",
      sortOrder: 5,
    },
  ],
};
