import type { FieldGroup } from "../types";

export const contentGroup: FieldGroup = {
  id: "content",
  label: "Content & Publishing",
  description:
    "Tell us about the articles, blogs, or media you plan to publish.",
  sortOrder: 6,
  step: 2,
  fields: [
    {
      id: "content.contentTypes",
      groupId: "content",
      type: "checkbox-group",
      label: "What types of content will you publish?",
      options: [
        { value: "blog", label: "Blog posts / articles" },
        { value: "news", label: "News or press releases" },
        { value: "videos", label: "Video content" },
        { value: "podcasts", label: "Podcasts or audio" },
        { value: "gallery", label: "Photo galleries" },
        { value: "resources", label: "Guides, whitepapers, or ebooks" },
      ],
      validation: { required: true, minItems: 1 },
      layout: "full",
      sortOrder: 1,
    },
    {
      id: "content.publishFrequency",
      groupId: "content",
      type: "select",
      label: "How often will you publish?",
      options: [
        { value: "daily", label: "Daily" },
        { value: "weekly", label: "Weekly" },
        { value: "biweekly", label: "Every two weeks" },
        { value: "monthly", label: "Monthly" },
        { value: "irregular", label: "No set schedule" },
      ],
      validation: { required: true },
      layout: "half",
      sortOrder: 2,
    },
    {
      id: "content.authors",
      groupId: "content",
      type: "select",
      label: "How many people will create content?",
      options: [
        { value: "1", label: "Just me" },
        { value: "2-5", label: "2–5 people" },
        { value: "6+", label: "6 or more" },
        { value: "guest", label: "We'll also have guest contributors" },
      ],
      validation: { required: true },
      layout: "half",
      sortOrder: 3,
    },
    {
      id: "content.features",
      groupId: "content",
      type: "checkbox-group",
      label: "What content features do you need?",
      options: [
        { value: "categories", label: "Categories and tags" },
        { value: "search", label: "Content search" },
        { value: "comments", label: "Reader comments" },
        { value: "newsletter", label: "Email newsletter integration" },
        { value: "social-share", label: "Social media sharing" },
        { value: "seo", label: "SEO tools (meta tags, sitemaps)" },
        { value: "scheduling", label: "Schedule posts to publish later" },
      ],
      validation: { required: false },
      layout: "full",
      sortOrder: 4,
    },
    {
      id: "content.existingContent",
      groupId: "content",
      type: "radio-group",
      label: "Do you have existing content to migrate?",
      options: [
        { value: "yes-lots", label: "Yes — a large archive" },
        { value: "yes-some", label: "Yes — a handful of posts" },
        { value: "no", label: "No — starting fresh" },
      ],
      validation: { required: true },
      layout: "half",
      sortOrder: 5,
    },
  ],
};
