import type { FieldGroup } from "../types";

export const designGroup: FieldGroup = {
  id: "design",
  label: "Design & Branding",
  description: "Help us understand your visual style so the result feels like you.",
  sortOrder: 1,
  step: 4,
  fields: [
    {
      id: "design.brandStatus",
      groupId: "design",
      type: "radio-group",
      label: "Do you have existing branding (logo, colors, fonts)?",
      options: [
        { value: "yes-full", label: "Yes — logo, colors, and fonts" },
        { value: "yes-partial", label: "Partially — just a logo or some colors" },
        { value: "no", label: "No — I need branding from scratch" },
        { value: "unsure", label: "Not sure" },
      ],
      validation: { required: true },
      layout: "full",
      sortOrder: 1,
    },
    {
      id: "design.brandColors",
      groupId: "design",
      type: "text",
      label: "Brand Colors",
      placeholder: "Navy blue, gold, white",
      helpText: "List colors or hex codes if you have them.",
      validation: { required: false, maxLength: 200 },
      layout: "half",
      sortOrder: 2,
    },
    {
      id: "design.brandVibe",
      groupId: "design",
      type: "checkbox-group",
      label: "What vibe should your site give off?",
      options: [
        { value: "professional", label: "Professional & corporate" },
        { value: "friendly", label: "Friendly & approachable" },
        { value: "bold", label: "Bold & edgy" },
        { value: "minimal", label: "Clean & minimal" },
        { value: "luxurious", label: "Luxurious & premium" },
        { value: "playful", label: "Playful & fun" },
        { value: "earthy", label: "Earthy & organic" },
        { value: "techy", label: "Modern & tech-forward" },
      ],
      validation: { required: false },
      layout: "full",
      sortOrder: 3,
    },
    {
      id: "design.inspirationSites",
      groupId: "design",
      type: "textarea",
      label: "Websites You Like",
      placeholder: "https://example.com — I love their layout and color scheme",
      helpText: "Paste URLs and note what you like about each one.",
      validation: { required: false, maxLength: 1000 },
      rows: 3,
      layout: "full",
      sortOrder: 4,
    },
    {
      id: "design.mustHaveContent",
      groupId: "design",
      type: "textarea",
      label: "Must-Have Pages or Content",
      placeholder: "Home, About, Services, Contact, FAQ...",
      helpText: "List the pages or sections you definitely need.",
      validation: { required: false, maxLength: 1000 },
      rows: 3,
      layout: "full",
      sortOrder: 5,
    },
  ],
};
