import type { FieldGroup } from "../types";

export const ecommerceGroup: FieldGroup = {
  id: "ecommerce",
  label: "Online Store Details",
  description:
    "Help us understand what you're selling and how your store should work.",
  sortOrder: 1,
  step: 3,
  fields: [
    {
      id: "ecommerce.whatYouSell",
      groupId: "ecommerce",
      type: "text",
      label: "What do you sell?",
      placeholder: "Handmade jewelry, digital templates, coffee beans...",
      validation: { required: true, maxLength: 200 },
      layout: "full",
      sortOrder: 1,
    },
    {
      id: "ecommerce.productCount",
      groupId: "ecommerce",
      type: "select",
      label: "How many products do you have?",
      options: [
        { value: "1-10", label: "1–10" },
        { value: "11-50", label: "11–50" },
        { value: "51-200", label: "51–200" },
        { value: "201-1000", label: "201–1,000" },
        { value: "1000+", label: "1,000+" },
      ],
      validation: { required: true },
      layout: "half",
      sortOrder: 2,
    },
    {
      id: "ecommerce.productType",
      groupId: "ecommerce",
      type: "radio-group",
      label: "What type of products?",
      options: [
        { value: "physical", label: "Physical products (shipped)" },
        { value: "digital", label: "Digital downloads" },
        { value: "both", label: "Both physical and digital" },
        { value: "services", label: "Services" },
      ],
      validation: { required: true },
      layout: "half",
      sortOrder: 3,
    },
    {
      id: "ecommerce.targetAudience",
      groupId: "ecommerce",
      type: "text",
      label: "Who is your target customer?",
      placeholder: "Women 25-45 who value sustainability...",
      validation: { required: false, maxLength: 300 },
      layout: "full",
      sortOrder: 4,
    },
    {
      id: "ecommerce.currentPlatform",
      groupId: "ecommerce",
      type: "select",
      label: "Current e-commerce platform (if any)",
      helpText: "Where you currently sell online, if anywhere.",
      options: [
        { value: "none", label: "None — starting fresh" },
        { value: "shopify", label: "Shopify" },
        { value: "woocommerce", label: "WooCommerce" },
        { value: "squarespace", label: "Squarespace" },
        { value: "etsy", label: "Etsy" },
        { value: "amazon", label: "Amazon" },
        { value: "other", label: "Other" },
      ],
      validation: { required: true },
      layout: "half",
      sortOrder: 5,
    },
    {
      id: "ecommerce.features",
      groupId: "ecommerce",
      type: "checkbox-group",
      label: "Which store features do you need?",
      options: [
        { value: "product-search", label: "Product search & filtering" },
        { value: "reviews", label: "Customer reviews" },
        { value: "wishlists", label: "Wishlists" },
        { value: "discounts", label: "Discount codes & promotions" },
        { value: "subscriptions", label: "Subscription / recurring orders" },
        { value: "inventory", label: "Inventory tracking" },
        { value: "multi-currency", label: "Multi-currency support" },
        { value: "abandoned-cart", label: "Cart recovery (remind customers about items they left)" },
      ],
      validation: { required: false },
      layout: "full",
      sortOrder: 6,
    },
    {
      id: "ecommerce.paymentMethods",
      groupId: "ecommerce",
      type: "checkbox-group",
      label: "Preferred payment methods",
      options: [
        { value: "credit-card", label: "Credit / debit cards" },
        { value: "paypal", label: "PayPal" },
        { value: "apple-pay", label: "Apple Pay / Google Pay" },
        { value: "afterpay", label: "Buy now, pay later (Afterpay, Klarna)" },
        { value: "crypto", label: "Cryptocurrency" },
        { value: "bank-transfer", label: "Bank transfer / ACH" },
      ],
      validation: { required: false },
      layout: "full",
      sortOrder: 7,
    },
    {
      id: "ecommerce.shippingNeeds",
      groupId: "ecommerce",
      type: "select",
      label: "Shipping complexity",
      options: [
        { value: "none", label: "No shipping (digital only)" },
        { value: "simple", label: "Flat rate / simple shipping" },
        { value: "calculated", label: "Carrier-calculated rates (UPS, FedEx, USPS)" },
        { value: "international", label: "International shipping needed" },
        { value: "unsure", label: "Not sure yet" },
      ],
      validation: { required: true },
      layout: "half",
      sortOrder: 8,
    },
    {
      id: "ecommerce.taxRequirements",
      groupId: "ecommerce",
      type: "select",
      label: "Tax handling",
      options: [
        { value: "us-only", label: "US sales tax only" },
        { value: "international", label: "International tax (VAT, GST)" },
        { value: "exempt", label: "Tax-exempt products (books, certain foods, etc.)" },
        { value: "unsure", label: "Not sure yet" },
      ],
      validation: { required: true },
      layout: "half",
      sortOrder: 9,
    },
  ],
};
