import type { FieldGroup } from "../types";

export const educationGroup: FieldGroup = {
  id: "education",
  label: "Education & Online Courses",
  description: "Tell us about the learning experience you want to offer.",
  sortOrder: 12,
  step: 2,
  fields: [
    {
      id: "education.educationType",
      groupId: "education",
      type: "select",
      label: "Type of education",
      options: [
        { value: "online-courses", label: "Online courses" },
        { value: "tutoring", label: "Tutoring / coaching" },
        { value: "school", label: "School or academy" },
        { value: "corporate-training", label: "Corporate training" },
        { value: "certification", label: "Certification programs" },
        { value: "workshops", label: "Workshops / bootcamps" },
      ],
      validation: { required: true },
      layout: "half",
      sortOrder: 1,
    },
    {
      id: "education.courseCount",
      groupId: "education",
      type: "select",
      label: "How many courses or programs?",
      options: [
        { value: "1-5", label: "1–5" },
        { value: "6-20", label: "6–20" },
        { value: "21-50", label: "21–50" },
        { value: "50+", label: "50+" },
      ],
      validation: { required: true },
      layout: "half",
      sortOrder: 2,
    },
    {
      id: "education.features",
      groupId: "education",
      type: "checkbox-group",
      label: "What education features do you need?",
      options: [
        { value: "video-lessons", label: "Video lessons" },
        { value: "quizzes", label: "Quizzes or assessments" },
        { value: "certificates", label: "Completion certificates" },
        { value: "progress", label: "Student progress tracking" },
        { value: "drip", label: "Scheduled content release (unlock lessons over time)" },
        { value: "community", label: "Student community / discussion" },
        { value: "payments", label: "Course payments / subscriptions" },
        { value: "bulk", label: "Group sign-ups / team licenses" },
      ],
      validation: { required: false },
      layout: "full",
      sortOrder: 3,
    },
    {
      id: "education.contentFormat",
      groupId: "education",
      type: "checkbox-group",
      label: "Content formats you'll use",
      options: [
        { value: "video", label: "Pre-recorded video" },
        { value: "live", label: "Live sessions (webinars, Zoom)" },
        { value: "text", label: "Written lessons / articles" },
        { value: "downloads", label: "Downloadable resources (PDFs, worksheets)" },
        { value: "interactive", label: "Interactive exercises" },
        { value: "audio", label: "Audio / podcast lessons" },
      ],
      validation: { required: true, minItems: 1 },
      layout: "full",
      sortOrder: 4,
    },
  ],
};
