import type { FieldGroup } from "../types";

export const eventsGroup: FieldGroup = {
  id: "events",
  label: "Events & Ticketing",
  description: "Help us understand the events you run.",
  sortOrder: 5,
  step: 2,
  fields: [
    {
      id: "events.eventTypes",
      groupId: "events",
      type: "text",
      label: "What types of events do you host?",
      placeholder: "Workshops, conferences, concerts, fundraisers...",
      validation: { required: true, maxLength: 300 },
      layout: "full",
      sortOrder: 1,
    },
    {
      id: "events.eventFrequency",
      groupId: "events",
      type: "select",
      label: "How often do you host events?",
      options: [
        { value: "weekly", label: "Weekly" },
        { value: "monthly", label: "Monthly" },
        { value: "quarterly", label: "A few times a year" },
        { value: "annually", label: "Once a year" },
        { value: "irregular", label: "No set schedule" },
      ],
      validation: { required: true },
      layout: "half",
      sortOrder: 2,
    },
    {
      id: "events.ticketing",
      groupId: "events",
      type: "radio-group",
      label: "Do you need to sell tickets online?",
      options: [
        { value: "yes", label: "Yes" },
        { value: "no", label: "No — free or invite-only events" },
        { value: "some", label: "Some events are ticketed" },
      ],
      validation: { required: true },
      layout: "half",
      sortOrder: 3,
    },
    {
      id: "events.features",
      groupId: "events",
      type: "checkbox-group",
      label: "What event features do you need?",
      options: [
        { value: "calendar", label: "Public event calendar" },
        { value: "registration", label: "Online registration / RSVP" },
        { value: "reminders", label: "Email reminders to attendees" },
        { value: "virtual", label: "Virtual / hybrid event support" },
        { value: "recurring", label: "Recurring event series" },
        { value: "speakers", label: "Speaker or performer profiles" },
        { value: "sponsors", label: "Sponsor showcase" },
      ],
      validation: { required: false },
      layout: "full",
      sortOrder: 4,
    },
    {
      id: "events.attendeeCount",
      groupId: "events",
      type: "select",
      label: "Typical event attendance",
      options: [
        { value: "1-25", label: "1–25 people" },
        { value: "26-100", label: "26–100 people" },
        { value: "101-500", label: "101–500 people" },
        { value: "500+", label: "500+" },
        { value: "varies", label: "Varies widely" },
      ],
      validation: { required: true },
      layout: "half",
      sortOrder: 5,
    },
  ],
};
