import type { FieldGroup } from "../types";

export const foodServiceGroup: FieldGroup = {
  id: "food-service",
  label: "Food & Restaurant",
  description:
    "Tell us about your food business so we can build the right experience.",
  sortOrder: 9,
  step: 3,
  fields: [
    {
      id: "food-service.businessType",
      groupId: "food-service",
      type: "select",
      label: "Type of food business",
      options: [
        { value: "restaurant", label: "Restaurant / dine-in" },
        { value: "cafe", label: "Café or coffee shop" },
        { value: "food-truck", label: "Food truck" },
        { value: "bakery", label: "Bakery" },
        { value: "catering", label: "Catering service" },
        { value: "ghost-kitchen", label: "Ghost kitchen (delivery-only, no dine-in)" },
        { value: "bar", label: "Bar or brewery" },
        { value: "other", label: "Other" },
      ],
      validation: { required: true },
      layout: "half",
      sortOrder: 1,
    },
    {
      id: "food-service.cuisineType",
      groupId: "food-service",
      type: "text",
      label: "Cuisine or specialty",
      placeholder: "Italian, BBQ, vegan, artisan baked goods...",
      validation: { required: false, maxLength: 200 },
      layout: "half",
      sortOrder: 2,
    },
    {
      id: "food-service.menuStyle",
      groupId: "food-service",
      type: "radio-group",
      label: "How do you want to show your menu?",
      options: [
        { value: "interactive", label: "Interactive menu with photos and prices" },
        { value: "pdf", label: "PDF menu download" },
        { value: "simple", label: "Simple text list" },
        { value: "unsure", label: "Not sure yet" },
      ],
      validation: { required: true },
      layout: "full",
      sortOrder: 3,
    },
    {
      id: "food-service.features",
      groupId: "food-service",
      type: "checkbox-group",
      label: "What restaurant features do you need?",
      options: [
        { value: "online-ordering", label: "Online ordering" },
        { value: "reservations", label: "Table reservations" },
        { value: "delivery", label: "Delivery tracking" },
        { value: "loyalty", label: "Loyalty / rewards program" },
        { value: "catering-form", label: "Catering request form" },
        { value: "gift-cards", label: "Gift cards" },
        { value: "dietary", label: "Dietary filter (vegan, GF, etc.)" },
      ],
      validation: { required: false },
      layout: "full",
      sortOrder: 4,
    },
    {
      id: "food-service.orderingIntegration",
      groupId: "food-service",
      type: "select",
      label: "Current online ordering platform (if any)",
      options: [
        { value: "none", label: "None" },
        { value: "doordash", label: "DoorDash" },
        { value: "ubereats", label: "Uber Eats" },
        { value: "grubhub", label: "Grubhub" },
        { value: "toast", label: "Toast" },
        { value: "square", label: "Square for Restaurants" },
        { value: "other", label: "Other" },
      ],
      validation: { required: true },
      layout: "half",
      sortOrder: 5,
    },
    {
      id: "food-service.locationCount",
      groupId: "food-service",
      type: "select",
      label: "Number of locations",
      options: [
        { value: "1", label: "1 location" },
        { value: "2-5", label: "2–5 locations" },
        { value: "6+", label: "6+ locations" },
      ],
      validation: { required: true },
      layout: "half",
      sortOrder: 6,
    },
  ],
};
