import type { FieldGroup } from "../types";

export const healthcareGroup: FieldGroup = {
  id: "healthcare",
  label: "Healthcare & Wellness",
  description:
    "Help us understand your practice so we can address compliance and patient needs.",
  sortOrder: 10,
  step: 3,
  fields: [
    {
      id: "healthcare.practiceType",
      groupId: "healthcare",
      type: "select",
      label: "Type of practice",
      options: [
        { value: "medical", label: "Medical / physician office" },
        { value: "dental", label: "Dental" },
        { value: "mental-health", label: "Mental health / therapy" },
        { value: "chiropractic", label: "Chiropractic" },
        { value: "physical-therapy", label: "Physical therapy" },
        { value: "veterinary", label: "Veterinary" },
        { value: "wellness", label: "Wellness / alternative medicine" },
        { value: "other", label: "Other" },
      ],
      validation: { required: true },
      layout: "half",
      sortOrder: 1,
    },
    {
      id: "healthcare.providerCount",
      groupId: "healthcare",
      type: "select",
      label: "Number of providers",
      options: [
        { value: "1", label: "Solo practitioner" },
        { value: "2-5", label: "2–5 providers" },
        { value: "6-20", label: "6–20 providers" },
        { value: "20+", label: "20+" },
      ],
      validation: { required: true },
      layout: "half",
      sortOrder: 2,
    },
    {
      id: "healthcare.features",
      groupId: "healthcare",
      type: "checkbox-group",
      label: "What healthcare site features do you need?",
      options: [
        { value: "provider-bios", label: "Provider bios and photos" },
        { value: "patient-portal", label: "Patient portal integration" },
        { value: "online-booking", label: "Online appointment booking" },
        { value: "telehealth", label: "Video appointment / remote care information" },
        { value: "services", label: "Services and conditions treated" },
        { value: "insurance", label: "Insurance accepted list" },
        { value: "testimonials", label: "Patient testimonials" },
        { value: "blog", label: "Health blog or resources" },
      ],
      validation: { required: false },
      layout: "full",
      sortOrder: 3,
    },
    {
      id: "healthcare.complianceConcerns",
      groupId: "healthcare",
      type: "checkbox-group",
      label: "Compliance considerations",
      helpText: "Select any that apply — we'll make sure the site meets requirements.",
      options: [
        { value: "hipaa", label: "HIPAA compliance" },
        { value: "ada", label: "ADA accessibility" },
        { value: "phi", label: "Protected health information (PHI) handling" },
        { value: "consent", label: "Patient consent forms" },
        { value: "none", label: "Not sure / none" },
      ],
      validation: { required: true, minItems: 1 },
      layout: "full",
      sortOrder: 4,
    },
    {
      id: "healthcare.patientFormNeeds",
      groupId: "healthcare",
      type: "radio-group",
      label: "Do you need online patient intake forms?",
      options: [
        { value: "yes", label: "Yes" },
        { value: "no", label: "No" },
        { value: "already-have", label: "We already use a separate system" },
      ],
      validation: { required: true },
      layout: "half",
      sortOrder: 5,
    },
  ],
};
