import type { FieldGroup } from "../types";

export const locationGroup: FieldGroup = {
  id: "location",
  label: "Locations & Service Areas",
  description: "Help us understand your physical presence.",
  sortOrder: 7,
  step: 2,
  fields: [
    {
      id: "location.locationCount",
      groupId: "location",
      type: "select",
      label: "How many locations do you have?",
      options: [
        { value: "1", label: "1 location" },
        { value: "2-5", label: "2–5 locations" },
        { value: "6-20", label: "6–20 locations" },
        { value: "20+", label: "20+" },
      ],
      validation: { required: true },
      layout: "half",
      sortOrder: 1,
    },
    {
      id: "location.locationType",
      groupId: "location",
      type: "checkbox-group",
      label: "What type of locations?",
      options: [
        { value: "retail", label: "Retail stores" },
        { value: "office", label: "Offices" },
        { value: "restaurant", label: "Restaurants or cafés" },
        { value: "warehouse", label: "Warehouses or fulfillment centers" },
        { value: "clinic", label: "Clinics or practices" },
        { value: "other", label: "Other" },
      ],
      validation: { required: true, minItems: 1 },
      layout: "half",
      sortOrder: 2,
    },
    {
      id: "location.features",
      groupId: "location",
      type: "checkbox-group",
      label: "What location features do you need?",
      options: [
        { value: "maps", label: "Embedded maps per location" },
        { value: "hours", label: "Individual hours for each location" },
        { value: "staff", label: "Staff directory per location" },
        { value: "locator", label: "Store locator (find locations by ZIP code or map)" },
        { value: "unique-pages", label: "Unique page per location" },
        { value: "reviews", label: "Location-specific reviews" },
      ],
      validation: { required: false },
      layout: "full",
      sortOrder: 3,
    },
    {
      id: "location.serviceArea",
      groupId: "location",
      type: "text",
      label: "What geographic area do you serve?",
      placeholder: "Greater Chicago area, nationwide, global...",
      validation: { required: false, maxLength: 200 },
      layout: "full",
      sortOrder: 4,
    },
  ],
};
