import type { FieldGroup } from "../types";

export const membershipGroup: FieldGroup = {
  id: "membership",
  label: "Membership & Gated Content",
  description: "Tell us about the members-only experience you want to create.",
  sortOrder: 4,
  step: 2,
  fields: [
    {
      id: "membership.memberTypes",
      groupId: "membership",
      type: "text",
      label: "What types of members will you have?",
      placeholder: "Free, Premium, VIP — or a single tier...",
      helpText: "List the tiers or types, even if tentative.",
      validation: { required: true, maxLength: 300 },
      layout: "full",
      sortOrder: 1,
    },
    {
      id: "membership.memberContent",
      groupId: "membership",
      type: "checkbox-group",
      label: "What will members get access to?",
      options: [
        { value: "articles", label: "Exclusive articles or posts" },
        { value: "videos", label: "Video content" },
        { value: "downloads", label: "Downloadable resources" },
        { value: "community", label: "Community forum or chat" },
        { value: "courses", label: "Courses or tutorials" },
        { value: "discounts", label: "Member discounts on products" },
        { value: "events", label: "Members-only events" },
      ],
      validation: { required: true, minItems: 1 },
      layout: "full",
      sortOrder: 2,
    },
    {
      id: "membership.expectedMembers",
      groupId: "membership",
      type: "select",
      label: "Expected number of members (first year)",
      options: [
        { value: "1-50", label: "1–50" },
        { value: "51-500", label: "51–500" },
        { value: "501-5000", label: "501–5,000" },
        { value: "5000+", label: "5,000+" },
        { value: "unsure", label: "Not sure yet" },
      ],
      validation: { required: true },
      layout: "half",
      sortOrder: 3,
    },
    {
      id: "membership.features",
      groupId: "membership",
      type: "checkbox-group",
      label: "What membership features do you need?",
      options: [
        { value: "paid-plans", label: "Paid subscription plans" },
        { value: "free-trial", label: "Free trial period" },
        { value: "drip-content", label: "Scheduled content release (unlock over time)" },
        { value: "member-directory", label: "Member directory" },
        { value: "progress-tracking", label: "Progress tracking" },
        { value: "certificates", label: "Completion certificates" },
      ],
      validation: { required: false },
      layout: "full",
      sortOrder: 4,
    },
  ],
};
