import type { FieldGroup } from "../types";

export const nonprofitGroup: FieldGroup = {
  id: "nonprofit",
  label: "Nonprofit & Donations",
  description: "Let's plan how to support your mission online.",
  sortOrder: 8,
  step: 2,
  fields: [
    {
      id: "nonprofit.orgType",
      groupId: "nonprofit",
      type: "select",
      label: "Type of organization",
      helpText: "Select the closest match — we can clarify later.",
      options: [
        { value: "501c3", label: "501(c)(3) charity (tax-exempt nonprofit)" },
        { value: "foundation", label: "Private foundation" },
        { value: "religious", label: "Religious organization" },
        { value: "social-enterprise", label: "Social enterprise" },
        { value: "advocacy", label: "Advocacy / political" },
        { value: "other", label: "Other nonprofit" },
      ],
      validation: { required: true },
      layout: "half",
      sortOrder: 1,
    },
    {
      id: "nonprofit.donationType",
      groupId: "nonprofit",
      type: "checkbox-group",
      label: "What types of donations will you accept?",
      helpText: "Select all that apply.",
      options: [
        { value: "one-time", label: "One-time donations" },
        { value: "recurring", label: "Monthly / recurring giving" },
        { value: "campaigns", label: "Campaign-specific fundraising" },
        { value: "peer-to-peer", label: "Peer-to-peer fundraising (supporters share your campaign with friends)" },
        { value: "in-kind", label: "In-kind donations (goods or services, not money)" },
        { value: "planned-giving", label: "Legacy gifts & wills" },
      ],
      validation: { required: true, minItems: 1 },
      layout: "full",
      sortOrder: 2,
    },
    {
      id: "nonprofit.features",
      groupId: "nonprofit",
      type: "checkbox-group",
      label: "What nonprofit site features do you need?",
      options: [
        { value: "donation-page", label: "Branded donation page" },
        { value: "impact", label: "Success stories showing your impact" },
        { value: "volunteer", label: "Volunteer sign-up" },
        { value: "events", label: "Fundraising events" },
        { value: "newsletter", label: "Email newsletter sign-up" },
        { value: "transparency", label: "Financial transparency section" },
      ],
      validation: { required: false },
      layout: "full",
      sortOrder: 3,
    },
    {
      id: "nonprofit.cmsNeeds",
      groupId: "nonprofit",
      type: "radio-group",
      label: "Do your staff need to update the site themselves?",
      options: [
        { value: "yes-often", label: "Yes — frequently" },
        { value: "yes-sometimes", label: "Yes — occasionally" },
        { value: "no", label: "No — we'll have a developer do it" },
      ],
      validation: { required: true },
      layout: "half",
      sortOrder: 4,
    },
    {
      id: "nonprofit.existingDonorPlatform",
      groupId: "nonprofit",
      type: "select",
      label: "Current donation platform (if any)",
      options: [
        { value: "none", label: "None" },
        { value: "stripe", label: "Stripe" },
        { value: "paypal", label: "PayPal Giving Fund" },
        { value: "donorbox", label: "Donorbox" },
        { value: "givebutter", label: "Givebutter" },
        { value: "classy", label: "Classy" },
        { value: "other", label: "Other" },
      ],
      validation: { required: true },
      layout: "half",
      sortOrder: 5,
    },
  ],
};
