import type { FieldGroup } from "../types";

export const portfolioGroup: FieldGroup = {
  id: "portfolio",
  label: "Portfolio & Showcase",
  description: "Let's plan how to display your best work.",
  sortOrder: 3,
  step: 2,
  fields: [
    {
      id: "portfolio.workType",
      groupId: "portfolio",
      type: "text",
      label: "What kind of work will you showcase?",
      placeholder: "Photography, architecture, graphic design...",
      validation: { required: true, maxLength: 200 },
      layout: "full",
      sortOrder: 1,
    },
    {
      id: "portfolio.itemCount",
      groupId: "portfolio",
      type: "select",
      label: "How many portfolio items do you have?",
      options: [
        { value: "1-10", label: "1–10" },
        { value: "11-30", label: "11–30" },
        { value: "31-100", label: "31–100" },
        { value: "100+", label: "100+" },
      ],
      validation: { required: true },
      layout: "half",
      sortOrder: 2,
    },
    {
      id: "portfolio.mediaTypes",
      groupId: "portfolio",
      type: "checkbox-group",
      label: "What media formats will you include?",
      options: [
        { value: "photos", label: "Photos / images" },
        { value: "videos", label: "Videos" },
        { value: "3d", label: "3D models or renders" },
        { value: "documents", label: "PDFs / documents" },
        { value: "audio", label: "Audio clips" },
        { value: "code", label: "Code samples / live demos" },
      ],
      validation: { required: true, minItems: 1 },
      layout: "full",
      sortOrder: 3,
    },
    {
      id: "portfolio.features",
      groupId: "portfolio",
      type: "checkbox-group",
      label: "What portfolio features do you need?",
      options: [
        { value: "categories", label: "Filter by category" },
        { value: "lightbox", label: "Lightbox / fullscreen view" },
        { value: "case-studies", label: "Detailed case study pages" },
        { value: "before-after", label: "Before & after comparisons" },
        { value: "password", label: "Password-protected projects" },
        { value: "download", label: "Downloadable files" },
      ],
      validation: { required: false },
      layout: "full",
      sortOrder: 4,
    },
    {
      id: "portfolio.clientTestimonials",
      groupId: "portfolio",
      type: "radio-group",
      label: "Will you include client testimonials?",
      options: [
        { value: "yes", label: "Yes" },
        { value: "no", label: "No" },
        { value: "later", label: "Maybe later" },
      ],
      validation: { required: true },
      layout: "half",
      sortOrder: 5,
    },
  ],
};
