import type { FieldGroup } from "../types";

export const realEstateGroup: FieldGroup = {
  id: "real-estate",
  label: "Real Estate & Property",
  description: "Tell us about your real estate business and listing needs.",
  sortOrder: 11,
  step: 3,
  fields: [
    {
      id: "real-estate.roleType",
      groupId: "real-estate",
      type: "select",
      label: "Your role in real estate",
      options: [
        { value: "agent", label: "Individual agent" },
        { value: "team", label: "Real estate team" },
        { value: "brokerage", label: "Brokerage" },
        { value: "developer", label: "Property developer" },
        { value: "management", label: "Property management" },
        { value: "investor", label: "Real estate investor" },
      ],
      validation: { required: true },
      layout: "half",
      sortOrder: 1,
    },
    {
      id: "real-estate.listingNeeds",
      groupId: "real-estate",
      type: "checkbox-group",
      label: "What property listing features do you need?",
      options: [
        { value: "idx", label: "MLS / property database integration" },
        { value: "featured", label: "Featured listings section" },
        { value: "search", label: "Property search with filters" },
        { value: "maps", label: "Map-based search" },
        { value: "virtual-tours", label: "Virtual tours / 3D walkthroughs" },
        { value: "calculators", label: "Mortgage calculators" },
      ],
      validation: { required: false },
      layout: "full",
      sortOrder: 2,
    },
    {
      id: "real-estate.features",
      groupId: "real-estate",
      type: "checkbox-group",
      label: "What additional site features do you need?",
      options: [
        { value: "agent-profiles", label: "Agent profiles and teams" },
        { value: "lead-capture", label: "Lead capture forms" },
        { value: "blog", label: "Market updates / blog" },
        { value: "neighborhoods", label: "Neighborhood guides" },
        { value: "testimonials", label: "Client testimonials" },
        { value: "crm", label: "CRM integration (contact management)" },
      ],
      validation: { required: false },
      layout: "full",
      sortOrder: 3,
    },
    {
      id: "real-estate.marketArea",
      groupId: "real-estate",
      type: "text",
      label: "Primary market area",
      placeholder: "Austin TX, South Florida, Bay Area...",
      validation: { required: true, maxLength: 200 },
      layout: "half",
      sortOrder: 4,
    },
    {
      id: "real-estate.mlsProvider",
      groupId: "real-estate",
      type: "text",
      label: "MLS provider (if applicable)",
      placeholder: "Bright MLS, ACTRIS, NTREIS...",
      helpText: "Your MLS system name — leave blank if you don't use one.",
      validation: { required: false, maxLength: 100 },
      layout: "half",
      sortOrder: 5,
    },
  ],
};
