import type { FieldGroup } from "../types";

export const saasGroup: FieldGroup = {
  id: "saas",
  label: "SaaS & Software Marketing",
  description:
    "Help us understand your software product so we can build a site that converts.",
  sortOrder: 13,
  step: 2,
  fields: [
    {
      id: "saas.productStage",
      groupId: "saas",
      type: "select",
      label: "Product stage",
      options: [
        { value: "idea", label: "Idea / pre-launch" },
        { value: "beta", label: "Beta" },
        { value: "launched", label: "Launched with users" },
        { value: "growth", label: "Growth stage" },
        { value: "enterprise", label: "Established / enterprise" },
      ],
      validation: { required: true },
      layout: "half",
      sortOrder: 1,
    },
    {
      id: "saas.siteType",
      groupId: "saas",
      type: "radio-group",
      label: "What does the site need to be?",
      options: [
        { value: "marketing", label: "Marketing / landing site" },
        { value: "docs", label: "Documentation site" },
        { value: "both", label: "Marketing + docs combined" },
        { value: "app-wrapper", label: "Wrapper around the app (login, pricing)" },
      ],
      validation: { required: true },
      layout: "full",
      sortOrder: 2,
    },
    {
      id: "saas.features",
      groupId: "saas",
      type: "checkbox-group",
      label: "What SaaS site features do you need?",
      options: [
        { value: "pricing-page", label: "Pricing comparison page" },
        { value: "demo-request", label: "Demo request form" },
        { value: "free-trial", label: "Free trial sign-up" },
        { value: "changelog", label: "Changelog / release notes" },
        { value: "integrations", label: "List of connected tools (Slack, Zapier, etc.)" },
        { value: "case-studies", label: "Customer case studies" },
        { value: "api-docs", label: "API documentation (for developers)" },
        { value: "status-page", label: "Status page" },
      ],
      validation: { required: false },
      layout: "full",
      sortOrder: 3,
    },
    {
      id: "saas.pricingModel",
      groupId: "saas",
      type: "select",
      label: "Pricing model",
      options: [
        { value: "free", label: "Free / open source" },
        { value: "freemium", label: "Freemium" },
        { value: "subscription", label: "Subscription" },
        { value: "per-seat", label: "Per seat / per user" },
        { value: "usage-based", label: "Usage-based" },
        { value: "one-time", label: "One-time purchase" },
        { value: "not-decided", label: "Haven't decided yet" },
      ],
      validation: { required: true },
      layout: "half",
      sortOrder: 4,
    },
    {
      id: "saas.targetCustomer",
      groupId: "saas",
      type: "select",
      label: "Target customer",
      helpText: "SMB = small/medium business. Mid-market = roughly 50–500 employees.",
      options: [
        { value: "consumer", label: "Consumers (B2C)" },
        { value: "smb", label: "Small businesses (SMB)" },
        { value: "mid-market", label: "Mid-market companies" },
        { value: "enterprise", label: "Enterprise" },
        { value: "developer", label: "Developers" },
        { value: "mixed", label: "Multiple segments" },
      ],
      validation: { required: true },
      layout: "half",
      sortOrder: 5,
    },
  ],
};
