import type { FieldGroup } from "../types";

export const schedulingGroup: FieldGroup = {
  id: "scheduling",
  label: "Appointments & Scheduling",
  description:
    "Tell us about the booking experience you want to offer clients.",
  sortOrder: 2,
  step: 2,
  fields: [
    {
      id: "scheduling.appointmentType",
      groupId: "scheduling",
      type: "text",
      label: "What types of appointments do you offer?",
      placeholder: "Consultations, haircuts, therapy sessions...",
      validation: { required: true, maxLength: 300 },
      layout: "full",
      sortOrder: 1,
    },
    {
      id: "scheduling.avgDuration",
      groupId: "scheduling",
      type: "select",
      label: "Average appointment length",
      options: [
        { value: "15min", label: "15 minutes" },
        { value: "30min", label: "30 minutes" },
        { value: "60min", label: "1 hour" },
        { value: "90min", label: "1.5 hours" },
        { value: "120min+", label: "2+ hours" },
        { value: "varies", label: "Varies by service" },
      ],
      validation: { required: true },
      layout: "half",
      sortOrder: 2,
    },
    {
      id: "scheduling.providerCount",
      groupId: "scheduling",
      type: "select",
      label: "How many staff members take bookings?",
      options: [
        { value: "1", label: "Just me" },
        { value: "2-5", label: "2–5 people" },
        { value: "6-20", label: "6–20 people" },
        { value: "20+", label: "20+" },
      ],
      validation: { required: true },
      layout: "half",
      sortOrder: 3,
    },
    {
      id: "scheduling.existingCalendar",
      groupId: "scheduling",
      type: "select",
      label: "Current booking tool (if any)",
      options: [
        { value: "none", label: "None — manual scheduling" },
        { value: "calendly", label: "Calendly" },
        { value: "acuity", label: "Acuity Scheduling" },
        { value: "google-calendar", label: "Google Calendar only" },
        { value: "square", label: "Square Appointments" },
        { value: "other", label: "Other" },
      ],
      validation: { required: true },
      layout: "half",
      sortOrder: 4,
    },
    {
      id: "scheduling.features",
      groupId: "scheduling",
      type: "checkbox-group",
      label: "What scheduling features do you need?",
      options: [
        { value: "online-booking", label: "Online self-service booking" },
        { value: "reminders", label: "Automated email/SMS reminders" },
        { value: "payments", label: "Collect payment at booking" },
        { value: "recurring", label: "Recurring appointments" },
        { value: "waitlist", label: "Waitlist management" },
        { value: "group", label: "Group/class bookings" },
        { value: "intake-forms", label: "Pre-appointment forms (collect client info before visit)" },
      ],
      validation: { required: false },
      layout: "full",
      sortOrder: 5,
    },
  ],
};
